title: ProofDx Gmail Signature.
description: Follow the instructions to set up your own Gmail signature! 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: false
